# theme: jekyll-theme-cayman
# New theme! Instructions at https://github.com/zivong/jekyll-theme-hydure
remote_theme: zivong/jekyll-theme-hydure
title: Pups and Pots
tagline: Hand-built and wheel-spun pottery in Boulder, CO
cover: images/wheel.jpg
